name: Update Stock Data

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-stocks:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Create stock data
      run: |
        mkdir -p docs
        python - <<EOF
        from datetime import datetime
        
        # Sample stock data
        stocks = [
            {"symbol": "SALIK", "price": "5.29", "change": "-0.06", "change_percentage": "-1.122"},
            {"symbol": "DTC", "price": "2.69", "change": "0.05", "change_percentage": "1.89"}
        ]
        
        # Create CSV content
        csv_content = 'Symbol,Price (AED),Change,Change %,Last Update\n'
        
        # Add each stock to CSV
        for stock in stocks:
            csv_content += f"{stock['symbol']},"
            csv_content += f"{stock['price']},"
            csv_content += f"{stock['change']},"
            csv_content += f"{stock['change_percentage']},"
            csv_content += f"{datetime.now().isoformat()}\n"
        
        # Save to file
        with open('docs/stocks.csv', 'w') as f:
            f.write(csv_content)
            
        print("Successfully created stocks.csv")
        EOF
        
    - name: Commit and push changes
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add docs/stocks.csv
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update stock data $(date +'%Y-%m-%d %H:%M:%S')" && git push)