name: Update Stock Data

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-stocks:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        
    - name: Fetch and update stock data
      run: |
        mkdir -p docs
        python - <<EOF
        import requests
        from datetime import datetime
        
        try:
            # Fetch data from your API
            response = requests.get("http://localhost:8000/api/v1/stocks")
            data = response.json()
            
            # Create CSV content
            csv_content = 'Symbol,Price (AED),Change,Change %,Last Update\n'
            for stock in data['stocks']:
                csv_content += f"{stock['symbol']},{stock['price']},{stock['change']},{stock['change_percentage'].replace('%','')},{datetime.now().isoformat()}\n"
            
            # Save to file
            with open('docs/stocks.csv', 'w') as f:
                f.write(csv_content)
                
            print("Successfully updated stocks.csv")
            
        except Exception as e:
            print(f"Error: {str(e)}")
            raise e
        EOF
        
    - name: Commit and push changes
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add docs/stocks.csv
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update stock data $(date +'%Y-%m-%d %H:%M:%S')" && git push)